name: CI\CD features -v2
on:
  push:
    branches:
      - 'features/*'
  workflow_dispatch:

jobs:
  copy_to_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up Git
        run: |
          git config --global user.name 'pauloribeiro16'
          git config --global user.email 'paulinhovsc16@gmail.com'

      - name: Checkout quality branch
        run: |
          git fetch origin quality
          git checkout quality || git checkout -b quality origin/quality

      - name: Merge to quality
        run: |
          git checkout quality || git checkout -b quality origin/quality
          git pull origin quality
          git merge ${{ env.branch_name }} --no-ff --no-edit --allow-unrelated-histories || git merge --abort
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/pauloribeiro16/aws-amt-site-pr.git quality
      
      - name: Run a multi-line script
        run: |
          echo "${{ secrets.AWS_AMT_VM_KEY }}" > chave.pem
          chmod 400 chave.pem
          ssh -o StrictHostKeyChecking=no -i chave.pem ubuntu@ec2-54-224-159-11.compute-1.amazonaws.com -t "cd /var/www/html/pr/aws-amt-site-pr/; sudo git pull; ls -la"
